# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:16
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leasingPortal', '0005_auto_20160701_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 2, 0, 16, 11, 852003, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suite',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 2, 0, 16, 33, 873089, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
