# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingPortal', '0009_remove_suite_date_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='date_available',
            field=models.DateField(null=True),
        ),
    ]
